version: '3.1'

services:
  database:
    image: mariadb
    restart: always
    volumes:
      - ./data/mariadb:/var/lib/mysql
    networks:
      - directus-network
    env_file:
      - ./.env
  directus-rest-api:
    image: directus/directus:9.0.0-rc.95
    restart: always
    networks:
      - reverse-proxy
      - directus-network
    env_file:
      - ./.env
    depends_on:
      - database
    labels:
      - traefik.enable=true
      - traefik.http.services.EASYSELLING.loadbalancer.server.port=8055
      - traefik.http.routers.EASYSELLING.rule=Host(`easyselling.maxencemottard.com`)
      - traefik.http.routers.EASYSELLING.entrypoints=http
      - traefik.http.routers.EASYSELLING.middlewares=https-redirect@file
      - traefik.http.routers.EASYSELLING-Https.rule=Host(`easyselling.maxencemottard.com`)
      - traefik.http.routers.EASYSELLING-Https.entrypoints=https
      - traefik.http.routers.EASYSELLING-Https.middlewares=security@file, compression@file
      - traefik.http.routers.EASYSELLING-Https.tls=true
      - traefik.http.routers.EASYSELLING-Https.tls.certresolver=letsencrypt


networks:
  directus-network:
  reverse-proxy:
    external: true

