name: Deploy on VPS
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Deploy on VPS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: burnett01/rsync-deployments@4.0
        with:
          switches: -avzr --delete --exclude=.env --exclude=serviceAccountKey.json
          path: ./
          remote_path: /root/easyselling-api-node/
          remote_host: ${{ secrets.HOST }}
          remote_port: ${{ secrets.PORT }}
          remote_user: ${{ secrets.USERNAME }}
          remote_key: ${{ secrets.SSH_KEY }}
      - uses: appleboy/ssh-action@v0.0.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd ./easyselling-api-node;
            docker-compose up --build --force-recreate --detach;
